config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: "users/confirmations" }
  resource :reports # Основной роут для отправки репортов по api
  root to: "home#index"

  post "select_locale", to: "application#select_locale"

  scope :panel, module: :panel, as: :panel do
    get "/", to: "projects#index", as: :home
    get "/profile", to: "users#profile", as: :profile

    resources :projects do
      get "settings", as: :settings
      get "history", as: :history
      resources :members, only: %i[index create]

      resources :test_reports, only: %i[new show] do
        get "status", as: :status
        resources :features, only: [], shallow: true do
          resources :scenarios, only: :index
        end
      end
    end

    # get '/', to: 'panel#home', as: :home
    get "/lists", to: "panel#lists", as: :lists
  end

  resources :public_projects, only: %i[index show]
  resources :demo_projects, only: %i[index new show create]
  resources :pages, only: [:show], constraints: lambda { |params|
    %w[instructions about].include?(params[:id])
  }
  # get '/public/projects/:project_id', to: 'public_projects#show'
  mount Sidekiq::Web => "/sidekiq"
end

app/controllers/public_projects_controller.rb
# frozen_string_literal: true

class PublicProjectsController < ApplicationController
  before_action :set_project, only: [:show]

  def index
    @public_projects = Project.where(public: true)
  end

  def show
    return render "public_projects/access_restricted" if @project.blank? || !@project.public?

    @documentation_facade = Panel::Projects::DocumentationFacade.new(@project, params)
  end

  private

  def set_project
    @project = Project.friendly.find(params[:id])
  end
end

app/views/public_projects/access_restricted.html.slim
p Sorry, or we don't have such project or this project is not public.

app/views/public_projects/index.html.slim
.separatorVertical--20

.container
  h1.title = t('public_projects').upcase_first

  - @public_projects.each do |public_project|
    = link_to public_project_path(public_project), class: 'projectsListItem'
      .projectsListItem__link = public_project.title

app/views/public_projects/show.html.slim
= render 'shared/demo_public_project'