config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: "users/confirmations" }
  resource :reports # Основной роут для отправки репортов по api
  root to: "home#index"

  post "select_locale", to: "application#select_locale"

  scope :panel, module: :panel, as: :panel do
    get "/", to: "projects#index", as: :home
    get "/profile", to: "users#profile", as: :profile

    resources :projects do
      get "settings", as: :settings
      get "history", as: :history
      resources :members, only: %i[index create]

      resources :test_reports, only: %i[new show] do
        get "status", as: :status
        resources :features, only: [], shallow: true do
          resources :scenarios, only: :index
        end
      end
    end

    # get '/', to: 'panel#home', as: :home
    get "/lists", to: "panel#lists", as: :lists
  end

  resources :public_projects, only: %i[index show]
  resources :demo_projects, only: %i[index new show create]
  resources :pages, only: [:show], constraints: lambda { |params|
    %w[instructions about].include?(params[:id])
  }
  # get '/public/projects/:project_id', to: 'public_projects#show'
  mount Sidekiq::Web => "/sidekiq"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/taggable.rb
# frozen_string_literal: true

module Taggable
  extend ActiveSupport::Concern

  included do
    has_many :taggings, as: :taggable
    has_many :tags, through: :taggings
  end
end

app/models/demo_project.rb
# frozen_string_literal: true

class DemoProject < Project
end

app/models/feature.rb
# frozen_string_literal: true

class Feature < ApplicationRecord
  include AvailableStatuses
  include Sluggable
  include Taggable

  belongs_to :test_report
  has_many :scenarios, dependent: :destroy
  # has_and_belongs_to_many :tags
  delegate :project, to: :test_report

  def slug_candidates
    [:name]
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  # Concerns
  include Sluggable

  # Callbacks
  after_create :create_token

  # Associations
  has_many :test_reports, dependent: :destroy
  has_many :user_project_settings, dependent: :destroy

  has_and_belongs_to_many :users

  # Validations
  validates :title, presence: true

  # Nested attributes
  accepts_nested_attributes_for :test_reports
  accepts_nested_attributes_for :user_project_settings

  def users_to_notify
    UserProjectSetting.notify_on_failures.where(project: self)
  end

  private

  def create_token
    update(token: to_sgid(expires: nil, for: Time.zone.now.to_s).to_s)
  end

  def slug_candidates
    [:title]
  end
end

app/models/scenario.rb
# frozen_string_literal: true

class Scenario < ApplicationRecord
  include AvailableStatuses
  include Taggable

  belongs_to :feature
  has_many :steps, dependent: :destroy
end

app/models/step.rb
# frozen_string_literal: true

class Step < ApplicationRecord
  include AvailableStatuses

  belongs_to :scenario
  enum cucumber_type: { background: 1, test: 2 }
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :taggings

  has_many :features, through: :taggings, source: :taggable,
                      source_type: "Feature"
  has_many :features, through: :taggings, source: :taggable,
                      source_type: "Scenario"
end

app/models/tagging.rb
# frozen_string_literal: true

class Tagging < ApplicationRecord
  self.table_name = "tagging"

  belongs_to :tag
  belongs_to :taggable, polymorphic: true
end

app/models/test_report.rb
# frozen_string_literal: true

class TestReport < ApplicationRecord
  enum source: { manual: 0, external: 1 }
  include AvailableStatuses
  include Taggable

  after_create :create_test_report_status

  has_one_attached :report_file, dependent: :destroy
  belongs_to :project
  has_many :features, dependent: :destroy
  has_many :scenarios, through: :features
  has_one :test_report_process, dependent: :destroy

  private

  def create_test_report_status
    TestReportProcess.create test_report: self, status: :created
  end
end

app/models/test_report_process.rb
# frozen_string_literal: true

class TestReportProcess < ApplicationRecord
  belongs_to :test_report
  enum status: { created: 1, processing: 2, processed_with_error: 3, processed_with_success: 4 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :name, presence: true

  has_and_belongs_to_many :projects
  has_many :test_reports, through: :projects
  has_many :features, through: :test_reports
  has_many :user_project_settings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/models/user_project_setting.rb
# frozen_string_literal: true

class UserProjectSetting < ApplicationRecord
  enum name: { notify_on_failures: 0 }

  belongs_to :project
  belongs_to :user
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  def select_locale
    cookies[:lang] = params[:lang] if I18n.locale_available?(params[:lang])
    redirect_to request.referer
  end

  def default_url_options
    { lang: I18n.locale }
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def set_locale
    locale = cookies[:lang] || (I18n.locale_available?(params[:lang]) ? params[:lang] : I18n.default_locale)
    I18n.locale = locale
  end
end

app/controllers/demo_projects_controller.rb
# frozen_string_literal: true

class DemoProjectsController < ApplicationController
  before_action :set_project, only: [:show]

  def index
    @form_model = DemoProject.new
    @form_model.test_reports.build
  end

  def show
    return render "public_projects/access_restricted" unless @project.present? && @project.is_a?(DemoProject)

    @documentation_facade = Panel::Projects::DocumentationFacade.new(@project, params)
  end

  def create
    demo_project = DemoProject.create new_demo_project_params
    test_report = demo_project.test_reports.last

    ParseReportWorker.perform_async(test_report.id)

    redirect_to demo_project_path(demo_project)

    # return render json: { success: true, data: {  } }
  end

  private

  def set_project
    @project = Project.friendly.find(params[:id])
  end

  def new_demo_project_params
    params.require(:demo_project).permit(:title, { test_reports_attributes: %i[report_file source] })
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def show
    raise StandardError, "unexpected partial request: #{params[:id]}" unless %w[instructions about].include? params[:id]

    render "pages/#{params[:id]}"
  end
end

app/controllers/public_projects_controller.rb
# frozen_string_literal: true

class PublicProjectsController < ApplicationController
  before_action :set_project, only: [:show]

  def index
    @public_projects = Project.where(public: true)
  end

  def show
    return render "public_projects/access_restricted" if @project.blank? || !@project.public?

    @documentation_facade = Panel::Projects::DocumentationFacade.new(@project, params)
  end

  private

  def set_project
    @project = Project.friendly.find(params[:id])
  end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  protect_from_forgery except: :create

  def new; end

  def create
    project = find_project
    return render json: { error: "Project not found" } if project.nil?

    test_report = project.test_reports.create report_file: params[:report], source: :external
    ParseReportWorker.perform_async(test_report.id)
    render json: { success: true, data: { reportPath: panel_project_path(project) } }
  end

  private

  def find_project
    Project.find_by(token: params[:token])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def uniq_css_class
    "#{controller_path.tr '/', '_'}_#{action_name}"
  end
end

app/views/panel_components/_header.html.slim
nav.bd-navbar.navbar.has-shadow.is-spaced
  .container
    .navbar-menu
      .navbar-start
        = render 'panel_components/logo'

        = link_to t('my_projects').upcase_first, panel_home_path, class: 'navbar-item'
      - if current_user
        .navbar-end
          .navbar-item = current_user.email
          = link_to panel_profile_path, class: 'headerMenuButton' do
            .headerMenuButton__item
            .headerMenuButton__item
            .headerMenuButton__item
          .navbar-item
            = render 'layouts/language_select'

/ .avatar
/   = image_pack_tag 'media/images/avatar.png', width: '24px'

app/views/panel_components/_logo.html.slim
= link_to root_path, class: 'logo' do
  .logo__line
    .logo__circle
    .logo__circle
    .logo__circle
  .logo__line.logo__line--centered
    .logo__circle

app/views/panel_components/_public_projects_header.html.slim
nav.bd-navbar.navbar.has-shadow.is-spaced
  .container
    .navbar-menu
      .navbar-start
        = render 'panel_components/logo'

        / = link_to t('home').titleize, panel_home_path, class: 'navbar-item'
        = link_to t('public_projects').upcase_first, public_projects_path,
          class: ['navbar-item', 'headerMenu__item', controller_name == 'public_projects' ? 'headerMenu__item--active': nil ]
        = link_to t('demo_projects.title').upcase_first, demo_projects_path,
          class: ['navbar-item', 'headerMenu__item', controller_name == 'demo_projects' ? 'headerMenu__item--active': nil ]
        = link_to t('instructions').upcase_first, page_path(id: 'instructions'),
          class: ['navbar-item', 'headerMenu__item', controller_name == 'pages' && params[:id] == 'instructions' ? 'headerMenu__item--active': nil ]
        = link_to t('about').upcase_first, page_path(id: 'about'),
          class: ['navbar-item', 'headerMenu__item', controller_name == 'pages' && params[:id] == 'about' ? 'headerMenu__item--active': nil ]

      .navbar-end
        .navbar-item
          = link_to panel_projects_path, class:'application-header__panelLink' do
            span = t('Open panel')
            = image_pack_tag 'media/images/play-button.svg', width: '16px', class: 'application-header__goIcon'
        .navbar-item
          = render 'layouts/language_select'

app/views/panel_components/_report.html.slim
- if @documentation_facade.ready_to_read
  - cache [@documentation_facade.test_report.test_report_process, params[:filter].to_s || {}, I18n.locale]
    .documentation__sidebar
      .documentationFilter
        - if @documentation_facade.test_report.status&.count > 1
          label = t('status').upcase_first
          = select "filter", "status",
            options_for_select(@documentation_facade.test_report.status, params.dig(:filter, :status)),
            { include_blank: true, multiple: true }

        - if @documentation_facade.test_report.tags.present?
          label = t('tags').upcase_first
          = select "filter", "tags",
            options_for_select(@documentation_facade.test_report.tags.map { |tag| [tag.title, tag.id] }, params.dig(:filter, :tags)),
            { include_blank: true, multiple: true, value: params.dig(:filter, :tags) }

      .leftMenu
        ul.leftMenu__items data-selector='testReport__features'
          - @documentation_facade.features.each do |feature|
            li.leftMenu__item data-feature-id=feature.id
              = feature.name

      .leftMenu__footer.leftMenuFooter
        .leftMenuFooter__paragraph = t('test_report.finished', count: @documentation_facade.finished_scenarios_count, failures_count: @documentation_facade.failures_count).upcase_first
        .leftMenuFooter__paragraph = t('test_report.last_check', last_check_ago: @documentation_facade.last_check_ago).upcase_first

    .documentation__content data-selector='scenariosList'

- else
  div = t('wait_till_report_processing')

app/views/shared/_demo_public_project.html.slim
.separatorVertical--20

.container
  h1.title = @project.title

.separatorVertical--20

.container.documentation
  = render 'panel_components/report'