config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: "users/confirmations" }
  resource :reports # Основной роут для отправки репортов по api
  root to: "home#index"

  post "select_locale", to: "application#select_locale"

  scope :panel, module: :panel, as: :panel do
    get "/", to: "projects#index", as: :home
    get "/profile", to: "users#profile", as: :profile

    resources :projects do
      get "settings", as: :settings
      get "history", as: :history
      resources :members, only: %i[index create]

      resources :test_reports, only: %i[new show] do
        get "status", as: :status
        resources :features, only: [], shallow: true do
          resources :scenarios, only: :index
        end
      end
    end

    # get '/', to: 'panel#home', as: :home
    get "/lists", to: "panel#lists", as: :lists
  end

  resources :public_projects, only: %i[index show]
  resources :demo_projects, only: %i[index new show create]
  resources :pages, only: [:show], constraints: lambda { |params|
    %w[instructions about].include?(params[:id])
  }
  # get '/public/projects/:project_id', to: 'public_projects#show'
  mount Sidekiq::Web => "/sidekiq"
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  # Concerns
  include Sluggable

  # Callbacks
  after_create :create_token

  # Associations
  has_many :test_reports, dependent: :destroy
  has_many :user_project_settings, dependent: :destroy

  has_and_belongs_to_many :users

  # Validations
  validates :title, presence: true

  # Nested attributes
  accepts_nested_attributes_for :test_reports
  accepts_nested_attributes_for :user_project_settings

  def users_to_notify
    UserProjectSetting.notify_on_failures.where(project: self)
  end

  private

  def create_token
    update(token: to_sgid(expires: nil, for: Time.zone.now.to_s).to_s)
  end

  def slug_candidates
    [:title]
  end
end

app/controllers/panel/members_controller.rb
# frozen_string_literal: true

module Panel
  class MembersController < PanelController
    before_action :set_project
    before_action :set_members

    def index; end

    def create
      email = params[:user][:email]
      name = params[:user][:name]
      @user_invite_command = UserInviteCommand.call(email, name, @project)

      render "panel/members/index"
    end

    private

    def set_project
      @project = Project.friendly.find(params[:project_id])
    end

    def set_members
      @members = @project.users
    end
  end
end

app/controllers/panel/panel_controller.rb
# frozen_string_literal: true

module Panel
  class PanelController < ApplicationController
    layout "panel"

    before_action :authenticate_user!

    def home; end

    def lists; end
  end
end

app/controllers/panel/projects_controller.rb
# frozen_string_literal: true

module Panel
  class ProjectsController < PanelController
    include ReportSearchable

    prepend_before_action :set_project, only: %i[update
                                                 show
                                                 edit
                                                 settings
                                                 documentation
                                                 history]

    def index
      @projects = current_user.projects.includes(:test_reports)
    end

    def update
      command_response = SaveProjectSettingsCommand.call(@project,
                                                         current_user.id,
                                                         project_params)

      redirect_to panel_project_settings_path(@project) if command_response.success?
    end

    def settings
      @user_project_settings = current_user
                                .user_project_settings
                                .where(project: @project)
    end

    def new
      @project = Project.new
    end

    def create
      command_response = CreateProjectCommand.call(project_params,
                                                   current_user)

      if command_response.success?
        redirect_to action: :index, notice: "Project was successfully updated."
      else
        render :new
      end
    end

    def history
      @test_reports = @project.test_reports
                              .limit(30)
                              .order(created_at: :desc)
    end

    def edit; end

    def project_params
      params.require(:project).permit(:title, :description, :public,
                                      { user_project_settings: [:notify_on_failures] })
    end

    def set_project
      @project = current_user.projects.friendly.find(params[:id] || params[:project_id])
    end
  end
end

app/controllers/panel/scenarios_controller.rb
# frozen_string_literal: true

module Panel
  class ScenariosController < PanelController
    skip_before_action :authenticate_user!

    # rubocop:disable Metrics/MethodLength
    def index
      # Only numbers are allowed for feature_id params.
      feature = Feature.find_by(id: params["feature_id"])

      project = feature.project

      view_variables = {
        feature: feature,
        scenarios: params[:status] ?
                       feature.scenarios.with_status(params[:status]) :
                       feature.scenarios
      }

      if current_user || project.public || project.is_a?(DemoProject)
        return render partial: "panel/projects/scenarios",
                      locals: view_variables
      end

      raise ActionController::Forbidden
    end
    # rubocop:enable Metrics/MethodLength
  end
end

app/controllers/panel/test_reports_controller.rb
# frozen_string_literal: true

module Panel
  class TestReportsController < PanelController
    before_action :set_project, only: %i[new status show]
    before_action :set_test_report, only: %i[status show]

    def new; end

    def show
      @documentation_facade = Panel::Projects::ShowTestReportFacade.new(@project, @test_report)
      render "panel/projects/show"
    end

    def status
      render json: {
        data: { status: @test_report.test_report_process.status }
      }
    end

    private

    def set_project
      @project = Project.friendly.find(params[:project_id])
    end

    def set_test_report
      @test_report = @project.test_reports.find(params[:test_report_id] || params[:id])
    end
  end
end

app/controllers/panel/users_controller.rb
# frozen_string_literal: true

module Panel
  class UsersController < PanelController
    def profile; end
  end
end

app/views/panel/projects/_form.html.slim
= form_with model: [:panel, @project], local: true do |f|
  .deviseForm__fieldSet
    / = @project.errors[:title]
    = f.label :title, class: 'deviseForm__label'
    = f.text_field :title, class: 'deviseForm__input'

  .deviseForm__fieldSet
    = f.label :description, class: 'deviseForm__label'
    = f.text_field :description, class: 'deviseForm__input'

  .deviseForm__fieldSet
    = f.label 'user_project_settings[notify_on_failures]', class: 'customCheckbox' do
      = f.check_box 'user_project_settings[notify_on_failures]',
        class: 'customCheckbox__input',
        checked: @user_project_settings&.find_by(name: 'notify_on_failures').present?
      .customCheckbox__checkboxIcon
      .customCheckbox__description =t('user.settings.notify_on_failures').upcase_first

  .deviseForm__fieldSet
    = f.label :public, class: 'customCheckbox' do
      = f.check_box :public, class: 'customCheckbox__input'
      .customCheckbox__checkboxIcon
      .customCheckbox__description =t('activerecord.attributes.project.public')

  .deviseForm__fieldSet
    = f.submit nil, class: 'button button--white deviseForm__submitButton'

app/views/panel/projects/_installation_instructions.en.html.slim
.installationInstructions
  h2.subtitle Typical steps for integration our system into your CI (Gitlab for example) system:

  .installationInstructions__step
    | Run tests using format with json report
    pre
      | cucumber:
      br
      |   stage: test
      br
      |   script:
      br
      |    - bundle exec cucumber --format json --out report.json --format pretty
      br
      |      artifacts:
      br
      |        paths:
      br
      |          - ./report.json
      br
      |        when: always

  .installationInstructions__step
    | Add gem which sends report to our service
    pre
      | gem 'documentation_world', git: 'https://gitlab.com/Rukomoynikov/documentation_world_gem.git'

  .installationInstructions__step
    | Send report to the selected project (example with )
    pre
      | documentation:
      br
      |    stage: documentation
      br
      |    script:
      br
      |      - bundle exec documentation_world send --token=#{ @project&.token || 'token' } --report './report.json'
      br
      |    when: master

app/views/panel/projects/_installation_instructions.ru.html.slim
.installationInstructions
  h2.subtitle Установка в вашу CI систему на примере Gitlab CI

  .installationInstructions__step
    | При прогоне тестов используйте допольнительный формат "json", ниже использовано сразу два формата обычный чтобы вы могли видеть результат как обычно, и генерация файла с отчетом:
    pre
      | cucumber:
      br
      |   stage: test
      br
      |   script:
      br
      |    - bundle exec cucumber --format json --out report.json --format pretty
      br
      |      artifacts:
      br
      |        paths:
      br
      |          - ./report.json
      br
      |        when: always

  .installationInstructions__step
    | Для того чтобы отправить файл нам можно использовать заготовленный нами gem, добавьте его в Gemfile:
    pre
      | gem 'documentation_world', git: 'https://gitlab.com/Rukomoynikov/documentation_world_gem.git'

  .installationInstructions__step
    | Отдельным шагом, например только для master ветки отправьте репорт нам. Используйте токен который можно найти в настройках проекта
    pre
      | documentation:
      br
      |    stage: documentation
      br
      |    script:
      br
      |      - bundle exec documentation_world send --token=#{ @project&.token || 'token' } --report './report.json'
      br
      |    when: master

app/views/panel/projects/_menu.html.slim
.tabs.is-centered.is-boxed
  ul
    li class=[('is-active' if action_name == 'show')]
      = link_to panel_project_path(@project)
        span = t('live_documentation').upcase_first
    li class=[('is-active' if action_name == 'history')]
      = link_to panel_project_history_path(@project)
        span = t('history').upcase_first
    li class=[('is-active' if action_name == 'settings')]
      = link_to panel_project_settings_path(@project)
        span = t('settings').upcase_first
    li class=[('is-active' if action_name == 'index' && controller_name == 'members' )]
      = link_to panel_project_members_path(@project)
        span = t('team').upcase_first

.separatorVertical--20

app/views/panel/projects/_scenarios.html.slim
- cache [feature, params[:status], params[:tags]]
  h1.title = feature.name
  .separatorVertical--8
  p = feature.description

  .separatorVertical--20
  - scenarios.each do |scenario|
    .featureBlock.collapsed [data-module-collapsed]
      .featureBlockHeader
        .featureBlockHeader__toggleStatusArrow
        .featureBlockHeader__title = scenario.name
        .featureBlockHeader__status
          - scenario.status.each do |status|
            .featureBlockHeader__statusCircle class="statusCircle statusCircle--#{ status }"
      .featureBlockContent
        - if scenario.tags.present?
          .featureBlockTags
            - scenario.tags.each do |tag|
              .featureBlockTags__tag = tag.title
        - if scenario.description.present?
          p.featureDescription = scenario.description
        .featureBlockContent__steps
          - scenario.steps.each do |step|
            .featureBlockStep
              .featureBlockStep__title #{ step.keyword } #{ step.name }
              .featureBlockStep__status
                - step.status.each do |status|
                  .featureBlockStep__statusCircle class="statusCircle statusCircle--#{ status }"

app/views/panel/projects/history.html.slim
.separatorVertical--20

.container
  h1.title = @project.title
  = render 'panel/projects/menu'

.separatorVertical--20

.container
  - @test_reports.each do |tr|
    = link_to panel_project_test_report_path(project_id: @project.id, id: tr),
      class: 'historyBlock' do
      .historyBlock__title Test report (#{ tr.features.with_status(:failed).count } failrues)
      span #{ time_ago_in_words(tr.created_at) } ago (#{ l(tr.created_at, format: :short) })

app/views/panel/projects/index.html.slim
.separatorVertical--20

.container.projects
  .projects__left
    h1.title = t('my_projects').upcase_first
  .projects__right
    = link_to t('add_project').upcase_first, new_panel_project_path, class: 'button button--white'

.separatorVertical--20

.container
  - @projects.each do |project|
    = link_to panel_project_path(project), class: 'projectsListItem'
      .projectsListItem__link = project.title
      - if project.test_reports.last.present?
        .projectsListItem__circles
          - project.test_reports.last.status.each do |status|
            div class="projectsListItem__circle statusCircle statusCircle--#{status}"

app/views/panel/projects/new.html.slim
.container--main.deviseForm
  h1.title New project

  = render 'panel/projects/form'

app/views/panel/projects/settings.html.slim
.separatorVertical--20

.container
  h1.title = @project.title
  = render 'panel/projects/menu'

.separatorVertical--20

.container
  h2.subtitle = t('project_settings').upcase_first

  .field
    label.label = t('token_long').upcase_first
    .control
      textarea.textarea(readonly) = @project.token
  hr


  = render 'panel/projects/form'

app/views/panel/projects/show.html.slim
.separatorVertical--20

.container
  .level
    .level-left
      h1.title = @project.title
    .level-right
      = link_to t('add_test_report').upcase_first, new_panel_project_test_report_path(@project), class: 'button'
  = render 'panel/projects/menu'

.container.documentation
  - if !@documentation_facade.test_report.present?
    = render 'panel/projects/installation_instructions'
  - else
    = render 'panel_components/report'